#+STARTUP: overview indent inlineimages logdrawer
#+OPTIONS: toc:nil TeX:t LaTeX:t
#+LANGUAGE: es

* Método de Avaliação
A avaliação neste curso será através de /EPs/ e /MiniEPs/.

- 2 EPs
- 3 MiniEPs

Também   gostaríamos  de   ser  avaliados   por   vocês  durante   o  curso,   e
disponibilizaremos alguns  questionários através dos  quais vocês vão  poder nos
avaliar e sugerir mudanças no curso.

#+TOC: headlines 2

** EPs
Teremos 2 EPs, ou tarefas mais longas,  a fim de aprofundar o conteúdo discutido
em aula.   Os EPs serão feitos  em grupos de  5 pessoas e suas  entregas deverão
incluir:

- Código fonte com a solução do problema proposto
- Um relatório detalhando e explicando a solução e os resultados encontrados

*** Médias de EPs (/Mep/)
A média dos EPs /Mep/ é dada por:

/Mep = (EP_1 + 2*EP_2)/ 3/


** Mini-EPs
Teremos 3 MiniEPs, ou tarefas  menores, abordando temas recentemente discutidos
em  aula.  Essas  tarefas também  serão realizadas  e entregues  em grupos  de 5
pessoas, e deverão incluir:

- Código fonte com a solução do problema proposto
- Um relatório detalhando e explicando a solução e os resultados encontrados

*** Notas dos mini-EPs (/Mm/)
Os mini-EPS têm *correção binária*, isto é, valem ou 10, ou 0.  A nota /Mm/ é a soma
das notas dos mini-EPs, dada por:

/Mm = (NmEP1 + NmEP2 + NmEP3)/ 3/

Onde /NmEP(1,2 e 3)/ são as notas dos mini-EPs.

** Cálculo da Nota Final
As notas  dos mini-EPs  (/Mmep/) e dos EPs (/Mep/) serão usadas no cálculo da nota final MF. Para ter aprovação no curso é
necessário ter nota final /MF >= 5.0/.

A média final MF é calculada da seguinte forma:

/MF = (Mm + 3Mep) / 4/
