#+STARTUP: overview indent inlineimages logdrawer
#+OPTIONS: toc:nil TeX:t LaTeX:t

* Método de Avaliação
A avaliação  neste  curso  será através de /EPs/,  /MiniEPs/  e /Seminários/ e
/Monografias/.

- 3 EPs
- 10 MiniEPs
- 1 Seminário

Também   gostaríamos  de   ser  avaliados   por   vocês  durante   o  curso,   e
disponibilizaremos alguns  questionários através dos  quais vocês vão  poder nos
avaliar e sugerir mudanças no curso.

** EPs
Teremos 3 EPs, ou tarefas mais longas,  a fim de aprofundar o conteúdo discutido
em aula.   Os EPs serão feitos  em grupos de  4 pessoas e suas  entregas deverão
incluir:

- Código fonte com a solução do problema proposto
- Um relatório detalhando e explicando a solução e os resultados encontrados
- Uma apresentação em slides que resuma o relatório

Na data da  entrega, 5 grupos serão sorteados para  apresentar suas soluções por
10 minutos, utilizando a apresentação em slides entregue.

** Mini-EPs
Teremos 10 MiniEPs, ou tarefas  menores, abordando temas recentemente discutidos
em  aula.  Essas  tarefas também  serão realizadas  e entregues  em grupos  de 4
pessoas, e deverão incluir:

- Código fonte com a solução do problema proposto
- Um relatório detalhando e explicando a solução e os resultados encontrados

** Seminários e Monografias
Também em grupos de  4 alunos, iremos disponibilizar uma lista  de temas e datas
para serem escolhidos por cada grupo.  Cada grupo deverá preparar uma monografia
e uma  apresentação sobre o  tema escolhido.   Todos os grupos  apresentarão, em
suas respectivas datas. Para essa tarefa deverão ser entregues:

- Uma monografia sobre o tema
- Uma apresentação em slides que resuma a monografia

** Cálculo da Nota Final
As notas  dos mini-EPs ($M_{m}$),  dos EPs ($M_{EP}$)  e dos Seminários  e Monografias
($M_{SM}$) serão  usadas no cálculo  da nota final  ($M_{F}$).  Para ter  aprovação no
curso é necessário ter nota final $M_{F} \geq 5.0$.

A média final $M_{F}$ é calculada da seguinte forma:

\[
M_F = (M_{m} + 2M_{SM} + 3M_{EP})  / 6
\]

** Médias de EPs ($M_{EP}$)
A média dos EPs $M_{EP}$ é dada por:

\[
M_{EP} = (EP_1 + EP_2 + EP_3) / 3
\]

** Notas dos Seminários e Monografias ($M_{SM}$)
Os Seminários e Monografias serão avaliados em uma única nota $M_{SM}$.
** Notas dos mini-EPs ($M_{m}$)
Os mini-EPS têm *correção binária*, isto é, valem ou $1$, ou $0$.  A nota $M_{m}$ é a
soma das notas dos mini-EPs, dada por:

\[
M_{m} = n_{mEP1} + \dots + n_{mEP10}
\]

Onde $n_{mEP1,\dots,10}$ são as notas dos mini-EPs.
